# Generated by Django 2.2.1 on 2019-05-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_auto_20190503_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingmessage',
            name='external_id',
        ),
    ]
