# Generated by Django 2.2.1 on 2019-05-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_remove_outgoingmessage_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='telegram.IncomingMessage'),
        ),
    ]
