# Generated by Django 2.2.1 on 2019-05-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_outgoingmessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='incomingmessage',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingmessage',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
