# Generated by Django 2.2.1 on 2019-05-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_auto_20190523_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingmessage',
            name='photo',
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='photo_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
