# Generated by Django 2.2.1 on 2019-05-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_auto_20190523_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='all_members_are_administrators',
        ),
    ]
