# Generated by Django 2.2.1 on 2019-05-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_remove_chat_all_members_are_administrators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='type',
        ),
    ]
