# Generated by Django 2.2.1 on 2019-05-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_remove_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='all_members_are_administrators',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='external_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
