# Generated by Django 2.2.1 on 2019-05-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0010_auto_20190524_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmessage',
            name='external_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='external_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
